# Mutations for Ether Cinema Data Connect

mutation CreateMovie(
  $title: String!
  $description: String!
  $posterUrl: String!
  $backdropUrl: String!
  $rating: Float!
  $videoId: String!
  $releaseYear: Int!
  $is4k: Boolean!
  $genre: String!
) @auth(level: USER) {
  movie_insert(data: {
    title: $title
    description: $description
    posterUrl: $posterUrl
    backdropUrl: $backdropUrl
    rating: $rating
    videoId: $videoId
    releaseYear: $releaseYear
    is4k: $is4k
    genre: $genre
  })
}

mutation SaveWatchHistory(
  $userId: String!
  $movieId: String!
  $positionMs: Int!
  $durationMs: Int!
) @auth(level: USER) {
  watchHistory_insert(data: {
    userId: $userId
    movieId: $movieId
    positionMs: $positionMs
    durationMs: $durationMs
  })
}
